### PR TITLE
Statistics panel only displays sites from the default project #306

### PR DESCRIPTION
**Pull request by ashklianko**
-There's no functionality neither in app-applications nor in backend to perform query in all available repos, thus have to handle this issue in different way, currently at least by mentioning in statistics panel that site info is related to default project

### CODE REVIEW

**Comment by sigdestad** [comment]
What about using multi-repo query?

**Comment by alansemenov** [comment]
> What about using multi-repo query?

We need to know which repos to query against in a multi-repo query.

**Comment by rymsha** [comment]
> We need to know which repos to query against in a multi-repo query.

**Comment by alansemenov** [comment]
These references are fetched not via JS API but via REST + content service:

https://github.com/enonic/xp/blob/f850ff1eb8de1c83d25fa4ba8983200b34f98e94/modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationInfoServiceImpl.java#L106
https://github.com/enonic/xp/blob/f850ff1eb8de1c83d25fa4ba8983200b34f98e94/modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java#L794

**Pull request merged**
